# Generated by Django 3.2.7 on 2021-10-18 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20211017_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countofingredient',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество ингредиентов не может быть меньше 1!')], verbose_name='Количество'),
        ),
    ]
