# Generated by Django 3.2.7 on 2021-10-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20211006_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countofingredient',
            name='recipe',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe', to='recipes.CountOfIngredient', verbose_name='Ингредиенты'),
        ),
    ]
