# Generated by Django 3.2.7 on 2021-10-08 21:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0007_auto_20211006_2017'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='countofingredient',
            unique_together={('ingredient', 'amount')},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'recipe')},
        ),
    ]
