# Generated by Django 3.2.7 on 2021-10-09 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211005_1325'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscribe',
            unique_together={('user', 'author')},
        ),
    ]
